version: '3.7'

services:
  tws:
    image: interactivebroker-gateway:v974
    build: docker-interactivebroker-gateway

    env_file:
      # The secrets file below contains the InteractiveBroker <username> and <password> variables.
      # Make sure not to insert spaces around the equals sign:
      # 
      # TWSUSERID=<username>
      # TWSPASSWORD=<password>
      #
      # Or if using FIX:
      # FIXUSERID=<username>
      # FIXPASSWORD=<password>
      #
      - ./secrets.conf

    ports:
      # Gateway API connection
      - "4003:4003"
      # VNC
      - "5901:5900"

    volumes:
      - ./ib-config/IBController.ini:/root/IBController/IBController.ini
      - ./ib-config/jts.ini:/root/Jts/jts.ini

    environment:
      - TZ=America/Chicago
      - VNC_PASSWORD=1234 # CHANGE ME
      - TRADING_MODE=paper # either paper or live
